#!/bin/sh
#
# Example script for passing-thru the GPS comms

# the netcat command needs to be in a separate executable, for the redirection
# to work correctly
sdptool add --channel=3 SP
sudo rfcomm listen rfcomm1 3 ./passthru2

