/* DO NOT EDIT!
   This file was automatically generated by /usr/bin/m68k-palmos-multigen v2.3
   from FlightMaster.def  */

	.file	"FlightMaster-sections.s"

	.globl	__text__
	.lcomm	__text__,4
	.globl	__text__section2
	.lcomm	__text__section2,4
	.globl	__text__section3
	.lcomm	__text__section3,4
	.globl	__text__section4
	.lcomm	__text__section4,4
	.globl	__text__section5
	.lcomm	__text__section5,4
	.globl	__text__section6
	.lcomm	__text__section6,4
	.globl	__text__section7
	.lcomm	__text__section7,4
	.globl	__text__section8
	.lcomm	__text__section8,4
	.globl	__text__section9
	.lcomm	__text__section9,4
	.globl	__text__sectio10
	.lcomm	__text__sectio10,4

.text
	.globl	_GccRelocateData
_GccRelocateData:
	bra.w	_GccLoadCodeAndRelocateData

.section ehook
	.long	_GccReleaseCode
